### ISSUE TITLE
Request to rename action

### ISSUE THREAD

**Issue by alerque** [nebularg/actions-luacheck#3]
Hey ... current maintainer of `luacheck` here.

I'm about to cut a new release. Among several new features is the ability to run LuaCheck as a GH Action directly from the official repository. Unfortunately I just discovered while drafting the release that GitHub won't allow me to name the action "Luacheck" because this repo is using that name for the action.

I'm wondering if we could convince you to rename this action to something else so the official upstream project can use the name directly. Note this does not entail renaming the repository, just the identifier in the action YAML config.

Thanks for the consideration...

**Comment by alerque** [comment]
Looking at the way this is implemented assuming an Ubuntu runner and installing apt packages, might I suggest:

```yaml
name: luacheck-runner
```

I'm sure there are other options. Note I don't think this change will require anything of people using the action since the `uses:` path to the repository will be the same, it will just affect how it shows up in the Actions Marketplace and in CI job logs.

**Comment by nebularg** [comment]
Sure, I don't mind

**Comment by nebularg** [comment]
It's all yours

**Comment by alerque** [comment]
Great, and thanks!

**Comment by alerque** [comment]
Did you mark the 1.1.1 release as "published" in the market place? It is still showing up there with the "luacheck" name and I am still unable to check off the "publish" button for a new draft release on the luacheck repo. I've never actually done this rename/reclaim dance before so I'm just guessing at what is required based on the messages I'm seeing. Sorry for the trouble.

**Comment by alerque** [comment]
![image](https://user-images.githubusercontent.com/173595/159759345-21137579-fd2a-485d-a670-5a6fea24ffc7.png)

Given that there doesn't seem to be a *luarocks* user or org in sight I'm assuming this action (still) having that *name* in the marketplace is the holdup. As for as I know this `name` key comes from the `action.yml` file. Given that the 'latest' version [in the marketplace view](https://github.com/marketplace/actions/luacheck) is still 1.1.0 I'm guessing the issue is that 'publish' checkbox — educated guess maybe but a guess none-the-less.

**Comment by nebularg** [comment]
Oh my bad, there was a new agreement I had to accept that disabled marketplace publishing. The name is free now

**Comment by alerque** [comment]
Thanks again. [Luacheck v0.26.0](https://github.com/lunarmodules/luacheck/releases/tag/v0.26.0) is released and [on the actions marketplace](https://github.com/marketplace/actions/luacheck).

By the way your implementation has some nice goodies like outputting the annotation format used by Actions. So for our upstream one just runs Luacheck without reformatting the output. That's something I'd like to implement as well if you have any interest in contributing. Given the Docker container format the implementation will be just a little bit different, but it could probably still be stuffed in the `action.yml`. Perhaps even more interesting though would be to use the TAP output formatter already built into Luacheck and see how GitHub likes that...
